pipeline:
  build-test-python:
    image: docker.twistbioscience-staging.com/devops_slave_python:3.6
    pull: true
    commands:
      - cd python
      - pip install invoke
      - inv install
      - flake8
      - inv test
    when:
      branch: [ develop, qa, staging, master ]