pipeline:
  build-test-python:
    image: docker.twistbioscience-staging.com/devops_slave_python:3.6
    pull: true
    commands:
      - cd python
      - pip install invoke
      - inv install
      - inv lint
      - inv test
    when:
      branch: [ master ]

  build-test-node:
    image: node:lts-alpine3.9
    pull: true
    commands:
      - cd node
      - npm install
      - npm run lint
      - npm run test
    when:
      branch: [ master ]

  build-test-ruby:
    image: docker.twistbioscience-staging.com/ecommerce_web:ruby-2.6.3
    pull: true
    commands:
      - cd ruby
      - gem install -g Gemfile
      - rubocop src tests *.rb
      - yardoc src/*
      - ruby -Ilib:test tests/test_*
    when:
      branch: [ master ]