config:
  categories:
    - GLOBAL
    - SYSTEM

env-vars:
  MANDATORY_INT:
    description: This is a mandatory env var that accepts only int values
    is_mandatory: true
    type: Int
  OPTIONAL_BOOL:
    description: This is an optional env var that accepts only boolean values (true, false, 0, 1)
    type: Bool
    default: false
  OPTIONAL_STRING:
    description: This is an optional env var that accepts any string value
    type: String
    default: Im a string
